Return-Path: <lhong@amnh.org>
X-Original-To: caml-list@yquem.inria.fr
Delivered-To: caml-list@yquem.inria.fr
Received: from mail1-relais-roc.national.inria.fr (mail1-relais-roc.national.inria.fr [192.134.164.82])
	by yquem.inria.fr (Postfix) with ESMTP id 93334BC57
	for <caml-list@yquem.inria.fr>; Mon, 21 Jun 2010 20:15:45 +0200 (CEST)
X-IronPort-Anti-Spam-Filtered: true
X-IronPort-Anti-Spam-Result: AgwCAHpJH0zYSfEMe2dsb2JhbACSYowlFQEBFiIEHsQQhRsE
X-IronPort-AV: E=Sophos;i="4.53,454,1272837600"; 
   d="scan'208";a="61830423"
Received: from info-smtp-004.amnh.org ([216.73.241.12])
  by mail1-smtp-roc.national.inria.fr with ESMTP; 21 Jun 2010 20:15:45 +0200
Received: from localhost (localhost.localdomain [127.0.0.1])
	by info-smtp-004.amnh.org (Postfix) with ESMTP id 6A5571CD525
	for <caml-list@yquem.inria.fr>; Mon, 21 Jun 2010 14:15:43 -0400 (EDT)
X-Virus-Scanned: amavisd-new at amnh.org
Received: from info-smtp-004.amnh.org ([127.0.0.1])
	by localhost (info-smtp-003.amnh.org [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id lkL5SLfVS6Mt for <caml-list@yquem.inria.fr>;
	Mon, 21 Jun 2010 14:15:42 -0400 (EDT)
Received: from webmail.amnh.org (dolce.amnh.org [216.73.241.32])
	by info-smtp-004.amnh.org (Postfix) with ESMTP id BF7E01CD563
	for <caml-list@yquem.inria.fr>; Mon, 21 Jun 2010 14:15:42 -0400 (EDT)
Received: from 216.73.250.152
        (SquirrelMail authenticated user lhong)
        by webmail.amnh.org with HTTP;
        Mon, 21 Jun 2010 14:15:42 -0400 (EDT)
Message-ID: <55271.216.73.250.152.1277144142.squirrel@webmail.amnh.org>
Date: Mon, 21 Jun 2010 14:15:42 -0400 (EDT)
Subject: exception error trace back in ocaml
From: "lin hong" <lhong@amnh.org>
To: caml-list@yquem.inria.fr
User-Agent: SquirrelMail/1.4.8-4.el4.centos
MIME-Version: 1.0
Content-Type: text/plain;charset=iso-8859-1
Content-Transfer-Encoding: 8bit
X-Priority: 3 (Normal)
Importance: Normal
X-Spam: no; 0.00; ocaml:01 amnh:01 traceback:01 traceback:01 ocaml:01 exception:01 exception:01 argument:02 bounds:02 raise:03 raise:03 hong:94 problem:05 looks:08 maybe:10 

Hi all,

I have problem getting a full traceback of some exception error. The
traceback looks like this:

Fatal error: exception Invalid_argument("index out of bounds")
Raised at file "camlinternalLazy.ml", line 33, characters 10-11
Called from file "list.ml", line 74, characters 24-34

But that's all I got, both camlinternalLazy.ml and list.ml are ocaml
source code, I still don't know which part of my code trigger it. Also, in
camlinternalLazy.ml line 33, there is a "try .... with e -> raise e", is
this the reason I don't have a full traceback -- Maybe something else
catch the "raise e" ?  Any idea?

Thanks.
Lin

