Received: (from weis@localhost) by pauillac.inria.fr (8.7.6/8.7.3) id SAA08847 for caml-redistribution; Mon, 6 Jul 1998 18:56:43 +0200 (MET DST)
Received: from concorde.inria.fr (concorde.inria.fr [192.93.2.39]) by pauillac.inria.fr (8.7.6/8.7.3) with ESMTP id OAA30224 for <caml-list@pauillac.inria.fr>; Sat, 4 Jul 1998 14:47:34 +0200 (MET DST)
Received: from pauillac.inria.fr (pauillac.inria.fr [128.93.11.35])
	by concorde.inria.fr (8.8.7/8.8.7) with ESMTP id OAA19176;
	Sat, 4 Jul 1998 14:47:31 +0200 (MET DST)
Received: (from xleroy@localhost) by pauillac.inria.fr (8.7.6/8.7.3) id OAA24642; Sat, 4 Jul 1998 14:47:31 +0200 (MET DST)
Message-ID: <19980704144731.05211@pauillac.inria.fr>
Date: Sat, 4 Jul 1998 14:47:31 +0200
From: Xavier Leroy <Xavier.Leroy@inria.fr>
To: "Michael Sperber [Mr. Preprocessor]" <sperber@informatik.uni-tuebingen.de>,
        caml-list@inria.fr
Subject: Re: Compiler internals question
References: <y9lbtr8lji5.fsf@brabantio.informatik.uni-tuebingen.de>
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
X-Mailer: Mutt 0.89.1
In-Reply-To: <y9lbtr8lji5.fsf@brabantio.informatik.uni-tuebingen.de>; from Michael Sperber [Mr. Preprocessor] on Thu, Jul 02, 1998 at 10:55:30AM +0200
Sender: weis

> (catch
>   (let (match/51 (apply (global f/49g) 5))
>     (catch
>       (switch match/51
>        case tag 1:
>         (let (match/52 (field 0 match/51) match/53 (field 1 match/51)) 17))
>      with exit))
>  with (raise (makeblock 0 (global Match_failure/12g) [0: "" 0 28])))
> 
> Does the inner "catch" serve any purpose or is it redundant?

It is redundant.  A latter pass (the translation from Lambda to
bytecode) will remove it by applying the equivalence (catch e with exit) == e.

- Xavier Leroy




